-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE DATABASE db_mercado01
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

COMMENT ON DATABASE db_mercado01
    IS 'Treinamento de banco de dados.';

USE db_mercado02;

CREATE TABLE IF NOT EXISTS public."TB_MERCADORIAS"
(
    "CD_MERCADORIA" integer NOT NULL,
    "DSC_MERCADORIA" character varying NOT NULL,
    "VL_COMPRA" numeric(5, 2) NOT NULL,
    "VL_VENDA" numeric(5, 2) NOT NULL,
    CONSTRAINT " CD_MERCADORIA_PK" PRIMARY KEY ("CD_MERCADORIA")
);

COMMENT ON TABLE public."TB_MERCADORIAS"
    IS 'Tabela que armazena informações referentes a mercadorias;';

CREATE TABLE IF NOT EXISTS public."TB_CLIENTES"
(
    "CD_CLIENTE" integer NOT NULL,
    "NM_CLIENTE" character varying NOT NULL,
    "DT_NASCIMENTO" date NOT NULL,
    "TP_DOCUMENTO" character varying NOT NULL,
    "NR_DOCUMENTO" character varying NOT NULL,
    "LOGRADOURO" character varying NOT NULL,
    "NUMERO" integer NOT NULL,
    "BAIRRO" character varying NOT NULL,
    "CIDADE" character varying NOT NULL,
    CONSTRAINT "CD_CLIENTE_PK" PRIMARY KEY ("CD_CLIENTE")
);

COMMENT ON TABLE public."TB_CLIENTES"
    IS 'Tabela que armazena informações sobre os clientes;';

CREATE TABLE IF NOT EXISTS public."TB_VENDAS"
(
    "CD_VENDA" integer NOT NULL,
    "NR_NF" character varying NOT NULL,
    "CD_CLIENTE" integer NOT NULL,
    "CD_MERCADORIA" integer NOT NULL,
    "QTD_VENDIDA" integer NOT NULL,
    "VL_TOTAL_MERCADORIA" numeric NOT NULL,
    PRIMARY KEY ("CD_VENDA")
);

COMMENT ON TABLE public."TB_VENDAS"
    IS 'Tabela que armazena informações de vendas';

CREATE TABLE IF NOT EXISTS public."TB_NOTA_FISCAL"
(
    "NR_NF" character varying NOT NULL,
    "DT_EMISSAO" date NOT NULL,
    "VL_TOTAL" numeric(5, 2) NOT NULL,
    CONSTRAINT "NR_NF_PK" PRIMARY KEY ("NR_NF")
);

COMMENT ON TABLE public."TB_NOTA_FISCAL"
    IS 'Tabela que armazena informações fiscais sumarizadas, como uma especie de tabela fato;';

ALTER TABLE IF EXISTS public."TB_VENDAS"
    ADD CONSTRAINT "CD_CLIENTE_FK" FOREIGN KEY ("CD_CLIENTE")
    REFERENCES public."TB_CLIENTES" ("CD_CLIENTE") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."TB_VENDAS"
    ADD CONSTRAINT "CD_MERCADORIA_FK" FOREIGN KEY ("CD_MERCADORIA")
    REFERENCES public."TB_MERCADORIAS" ("CD_MERCADORIA") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."TB_VENDAS"
    ADD CONSTRAINT "NR_NF_FK" FOREIGN KEY ("NR_NF")
    REFERENCES public."TB_NOTA_FISCAL" ("NR_NF") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;